/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface PurchaseOrder {
  'id' : string,
  'status' : OrderStatus,
  'customer' : Principal,
  'scooterModelId' : string,
  'timestamp' : bigint,
  'quantity' : bigint,
  'totalPrice' : bigint,
}
export interface ScooterModel {
  'id' : string,
  'chargingTime' : bigint,
  'name' : string,
  'image' : ExternalBlob,
  'price' : bigint,
  'topSpeed' : bigint,
  'range' : bigint,
}
export interface ServiceAppointment {
  'id' : string,
  'status' : string,
  'serviceType' : ServiceType,
  'customer' : Principal,
  'date' : string,
  'timestamp' : bigint,
  'timeSlot' : string,
}
export type ServiceType = { 'maintenance' : null } |
  { 'repairs' : null } |
  { 'batteryReplacement' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TestRideBooking {
  'id' : string,
  'status' : string,
  'customer' : Principal,
  'date' : string,
  'scooterModelId' : string,
  'timestamp' : bigint,
  'timeSlot' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addScooterModel' : ActorMethod<[ScooterModel], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookServiceAppointment' : ActorMethod<[ServiceAppointment], undefined>,
  'bookTestRide' : ActorMethod<[TestRideBooking], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[PurchaseOrder], undefined>,
  'deleteScooterModel' : ActorMethod<[string], undefined>,
  'getAllOrders' : ActorMethod<[], Array<PurchaseOrder>>,
  'getAllServiceAppointments' : ActorMethod<[], Array<ServiceAppointment>>,
  'getAllTestRides' : ActorMethod<[], Array<TestRideBooking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<PurchaseOrder>>,
  'getMyServiceAppointments' : ActorMethod<[], Array<ServiceAppointment>>,
  'getMyTestRides' : ActorMethod<[], Array<TestRideBooking>>,
  'getScooterModels' : ActorMethod<[], Array<ScooterModel>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateScooterModel' : ActorMethod<[ScooterModel], undefined>,
  'updateServiceAppointmentStatus' : ActorMethod<[string, string], undefined>,
  'updateTestRideStatus' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];