/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ScooterModel = IDL.Record({
  'id' : IDL.Text,
  'chargingTime' : IDL.Nat,
  'name' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
  'topSpeed' : IDL.Nat,
  'range' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'maintenance' : IDL.Null,
  'repairs' : IDL.Null,
  'batteryReplacement' : IDL.Null,
});
export const ServiceAppointment = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'serviceType' : ServiceType,
  'customer' : IDL.Principal,
  'date' : IDL.Text,
  'timestamp' : IDL.Int,
  'timeSlot' : IDL.Text,
});
export const TestRideBooking = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'customer' : IDL.Principal,
  'date' : IDL.Text,
  'scooterModelId' : IDL.Text,
  'timestamp' : IDL.Int,
  'timeSlot' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PurchaseOrder = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'customer' : IDL.Principal,
  'scooterModelId' : IDL.Text,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'totalPrice' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addScooterModel' : IDL.Func([ScooterModel], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookServiceAppointment' : IDL.Func([ServiceAppointment], [], []),
  'bookTestRide' : IDL.Func([TestRideBooking], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func([PurchaseOrder], [], []),
  'deleteScooterModel' : IDL.Func([IDL.Text], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
  'getAllServiceAppointments' : IDL.Func(
      [],
      [IDL.Vec(ServiceAppointment)],
      ['query'],
    ),
  'getAllTestRides' : IDL.Func([], [IDL.Vec(TestRideBooking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
  'getMyServiceAppointments' : IDL.Func(
      [],
      [IDL.Vec(ServiceAppointment)],
      ['query'],
    ),
  'getMyTestRides' : IDL.Func([], [IDL.Vec(TestRideBooking)], ['query']),
  'getScooterModels' : IDL.Func([], [IDL.Vec(ScooterModel)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateScooterModel' : IDL.Func([ScooterModel], [], []),
  'updateServiceAppointmentStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTestRideStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ScooterModel = IDL.Record({
    'id' : IDL.Text,
    'chargingTime' : IDL.Nat,
    'name' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
    'topSpeed' : IDL.Nat,
    'range' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'maintenance' : IDL.Null,
    'repairs' : IDL.Null,
    'batteryReplacement' : IDL.Null,
  });
  const ServiceAppointment = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'serviceType' : ServiceType,
    'customer' : IDL.Principal,
    'date' : IDL.Text,
    'timestamp' : IDL.Int,
    'timeSlot' : IDL.Text,
  });
  const TestRideBooking = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'customer' : IDL.Principal,
    'date' : IDL.Text,
    'scooterModelId' : IDL.Text,
    'timestamp' : IDL.Int,
    'timeSlot' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PurchaseOrder = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'customer' : IDL.Principal,
    'scooterModelId' : IDL.Text,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'totalPrice' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addScooterModel' : IDL.Func([ScooterModel], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookServiceAppointment' : IDL.Func([ServiceAppointment], [], []),
    'bookTestRide' : IDL.Func([TestRideBooking], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func([PurchaseOrder], [], []),
    'deleteScooterModel' : IDL.Func([IDL.Text], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
    'getAllServiceAppointments' : IDL.Func(
        [],
        [IDL.Vec(ServiceAppointment)],
        ['query'],
      ),
    'getAllTestRides' : IDL.Func([], [IDL.Vec(TestRideBooking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
    'getMyServiceAppointments' : IDL.Func(
        [],
        [IDL.Vec(ServiceAppointment)],
        ['query'],
      ),
    'getMyTestRides' : IDL.Func([], [IDL.Vec(TestRideBooking)], ['query']),
    'getScooterModels' : IDL.Func([], [IDL.Vec(ScooterModel)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateScooterModel' : IDL.Func([ScooterModel], [], []),
    'updateServiceAppointmentStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTestRideStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };